## 《Python数据挖掘方法及应用》PyDm
### 【第1章 数据收集与分析软件】数据与练习1 answer


---

1.1  下面有三组数据：

    1, 2, 3, 4, 5 
    a, b, c, d
    physics, chemistry, 1997, 2000

In [1]:
# (1)将其写入列表
array1 = [1, 2, 3, 4, 5]
array2 = ['a', 'b', 'c', 'd']
array3 = ['physics', 'chemistry', '1997', '2000']


# (2)将其写入字典


1.2  请创建下列Python数组，并计算。

In [2]:
#(1)创建一个2*2的数组，计算对角线上元素的和。
import numpy as np
arr = np.random.randint(0,10,size=(2,2))
n1 = arr[0,0]
n2 = arr[1,1]
m = n1+n2
print(arr)
print(m)

[[9 3]
 [4 6]]
15


In [3]:
#(2)创建一个长度为9的一维数据，数组元素为0～8，并将它重新变为3*3的二维数组。
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#(3)创建两个3*3的数组，分别将它们合并为3*6、6*3的数组后，拆分为3个数组。
import numpy as np
arr1 = np.random.randint(0,10,size=(3,3))
arr2 = np.random.randint(0,10,size=(3,3))
arr3 = np.hstack((arr1,arr2))
arr4 = np.vstack((arr1,arr2))
arr5,arr6,arr7 = np.split(arr3,3,axis=0)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)

[[6 5 7 2 5 5]
 [3 4 1 4 7 5]
 [4 2 3 6 9 0]]
[[6 5 7]
 [3 4 1]
 [4 2 3]
 [2 5 5]
 [4 7 5]
 [6 9 0]]
[[6 5 7 2 5 5]]
[[3 4 1 4 7 5]]
[[4 2 3 6 9 0]]


1.3  文本数据。下面有一些文本数据：

     name,physics,Python,math,english
     Google,100,100,25,12
     Facebook,45,54,44,88
     Twitter,54,76,13,91
     Yahoo,54,452,26,100 

In [5]:
#(1)请将其写入列表。
list = [['Google',100,100,25,12],['Facebook',45,54,44,88],['Twitter',54,76,13,91],['Yahoo',54,452,26,100]]
print(list)

[['Google', 100, 100, 25, 12], ['Facebook', 45, 54, 44, 88], ['Twitter', 54, 76, 13, 91], ['Yahoo', 54, 452, 26, 100]]


In [6]:
#(2)请将其写入字典。
dict = {'physics':{'Google':100,'Facebook':45,'Twitter':54,'Yahoo':54},
       'Python':{'Google':100,'Facebook':54,'Twitter':76,'Yahoo':452},
       'math':{'Google':25,'Facebook':44,'Twitter':13,'Yahoo':26},
       'english':{'Google':12,'Facebook':88,'Twitter':91,'Yahoo':100}}
print(dict['physics'])
print(dict['math']['Google'])

{'Google': 100, 'Facebook': 45, 'Twitter': 54, 'Yahoo': 54}
25


In [7]:
#(3)请将其写入数据框。
from pandas import DataFrame
dict = {'physics':{'Google':100,'Facebook':45,'Twitter':54,'Yahoo':54},
       'Python':{'Google':100,'Facebook':54,'Twitter':76,'Yahoo':452},
       'math':{'Google':25,'Facebook':44,'Twitter':13,'Yahoo':26},
       'english':{'Google':12,'Facebook':88,'Twitter':91,'Yahoo':100}}
dataframe = DataFrame(dict)
print(dataframe)

          physics  Python  math  english
Facebook       45      54    44       88
Google        100     100    25       12
Twitter        54      76    13       91
Yahoo          54     452    26      100


In [8]:
#(4)请将其保存到csv格式的文档，并从read_csv()函数读入Python。
import pandas
dict = {'physics':{'Google':100,'Facebook':45,'Twitter':54,'Yahoo':54},
       'Python':{'Google':100,'Facebook':54,'Twitter':76,'Yahoo':452},
       'math':{'Google':25,'Facebook':44,'Twitter':13,'Yahoo':26},
       'english':{'Google':12,'Facebook':88,'Twitter':91,'Yahoo':100}}
dataframe = pandas.DataFrame(dict)
dataframe.to_csv("grades.csv",index=True,sep=",")
data = pandas.read_csv("grades.csv")

1.4  调查数据。某公司对财务部门人员的抽烟状况进行调查，结果为：

    否，否，否，是，是，否，否，是，否，是，否，否，是，是，否，是，否，否，是，是。

In [9]:
#(1)请用列表录入该数据。
list = ['否','否','否','是','是','否','否','是','否','是','否','否','是','是','否','是','否','否','是','是']

In [11]:
!pip install xlwt


    100% |████████████████████████████████| 102kB 424kB/s a 0:00:011
You are using pip version 9.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [12]:
#(2)请将这组数据输入电子表格，并将其读入Python。
import pandas as pd
dict1 = {'抽烟情况':{1:'否',2:'否',3:'否',4:'是',5:'是',6:'否',7:'否',8:'是',9:'否',10:'是',11:'否',12:'否',13:'是',14:'是',15:'否',16:'是',17:'否',18:'否',19:'是',20:'是'}}
df = pandas.DataFrame(dict1)
df.to_excel("smoking-condition.xls",index=True)
data = pandas.read_excel("smoking-condition.xls")
#本地可运行，这个平台缺少“xlwt”库

1.5  学生成绩。从某大学统计系的学生中随机抽取24人，对数学和统计学的考试成绩进行调查，数据如表1-7所列。

In [14]:
! pip install openpyxl


    100% |████████████████████████████████| 245kB 137kB/s ta 0:00:01
/opt/conda/lib/python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
  Running setup.py bdist_wheel for et-xmlfile ... done
  Stored in directory: /home/kesci/.cache/pip/wheels/2a/77/35/0da0965a057698121fc7d8c5a7a9955cdbfb3cc4e2423cad39
Successfully built et-xmlfile
You are using pip version 9.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [15]:
#(1)试将这组数据输入电子表格。
array = [["编号","性别","数学","统计学"],
        ["1","M","81","72"],
        ["2","F","90","90"],
        ["3","F","91","96"],
        ["4","M","74","68"],
        ["5","F","70","82"],
        ["6","F","73","78"],
        ["7","M","88","89"],
        ["8","M","78","82"],
        ["9","M","95","96"],
        ["10","F","63","75"],
        ["11","F","85","86"],
        ["12","M","60","71"],
        ["13","F","83","78"],
        ["14","F","81","94"],
        ["15","M","77","73"],
        ["16","M","60","66"],
        ["17","F","66","58"],
        ["18","M","84","87"],
        ["19","F","80","86"],
        ["20","F","85","84"],
        ["21","M","70","82"],
        ["22","M","54","56"],
        ["23","F","93","98"],
        ["24","M","68","76"],]
import openpyxl
 
 
def write_excel_xlsx(path, sheet_name, value):
    index = len(value)
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = sheet_name
    for i in range(0, index):
        for j in range(0, len(value[i])):
            sheet.cell(row=i+1, column=j+1, value=str(value[i][j]))
    workbook.save(path)
    print("xlsx格式表格写入数据成功！")

write_excel_xlsx("部分学生的数学和统计学考试成绩.xlsx", "部分学生的数学和统计学考试成绩", array)
#本地可运行，这里运行缺少一个“openpyxl”库

xlsx格式表格写入数据成功！


In [16]:
#(2)分别用Python 的read_csv()和read_excel()函数读取。
import pandas as pd
DTgrades = pd.read_excel("部分学生的数学和统计学考试成绩.xlsx")
DTgrades1 = DTgrades.to_csv("部分学生的数学和统计学考试成绩.csv")#将.xlsx的文件转化成为.csv的文件储存在根目录下
DTgrades2 = DTgrades.to_csv("部分学生的数学和统计学考试成绩.csv")


In [17]:
#(3)用Python方法获取性别、数学和统计学成绩变量，并筛选不同性别学生的成绩。
DTgrades[["性别","数学","统计学"]]


性别  数学  统计学
0   M  81   72
1   F  90   90
2   F  91   96
3   M  74   68
4   F  70   82
5   F  73   78
6   M  88   89
7   M  78   82
8   M  95   96
9   F  63   75
10  F  85   86
11  M  60   71
12  F  83   78
13  F  81   94
14  M  77   73
15  M  60   66
16  F  66   58
17  M  84   87
18  F  80   86
19  F  85   84
20  M  70   82
21  M  54   56
22  F  93   98
23  M  68   76

In [20]:
gender = input('输入你想筛选学生成绩的性别(F/M):')
DTgrades.loc[(DTgrades['性别'] == gender)]

输入你想筛选学生成绩的性别(F/M):: M

编号 性别  数学  统计学
0    1  M  81   72
3    4  M  74   68
6    7  M  88   89
7    8  M  78   82
8    9  M  95   96
11  12  M  60   71
14  15  M  77   73
15  16  M  60   66
17  18  M  84   87
20  21  M  70   82
21  22  M  54   56
23  24  M  68   76

In [19]:
#(4)请在电子表格和Python中分别对性别、数学或统计学成绩排序。
standard = input("请输入你想要根据什么条件将成绩排序（性别/数学/统计学）：")
DTgrades.sort_values(by = standard)
#本地可运行

请输入你想要根据什么条件将成绩排序（性别/数学/统计学）：: 性别

编号 性别  数学  统计学
1    2  F  90   90
2    3  F  91   96
4    5  F  70   82
5    6  F  73   78
19  20  F  85   84
18  19  F  80   86
9   10  F  63   75
10  11  F  85   86
22  23  F  93   98
12  13  F  83   78
13  14  F  81   94
16  17  F  66   58
0    1  M  81   72
21  22  M  54   56
20  21  M  70   82
17  18  M  84   87
11  12  M  60   71
14  15  M  77   73
8    9  M  95   96
7    8  M  78   82
6    7  M  88   89
3    4  M  74   68
15  16  M  60   66
23  24  M  68   76